<?php

namespace Innertia\Platform\Organizations\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Innertia\Platform\Organizations\OrganizationsFeature;

/**
 * Generates a single consolidated migration that:
 *   - Adds `organization_id` (nullable bigint) to every table declared in
 *     config('innertia.organizations.tables').
 *   - Adds `organization_id` to `roles` and `model_roles` (RBAC scope).
 *   - Adds a composite (tenant_id, organization_id) index when the table has tenant_id,
 *     otherwise a single-column index on organization_id.
 *
 * Guard: refuses to run unless the Organizations feature is active
 * (config('innertia.organizations.enabled')=true AND config('innertia.mode')!=='api').
 * Idempotent: re-running detects existing `*_add_organization_id_*.php` and skips.
 */
class OrganizationInstallCommand extends Command
{
    protected $signature   = 'innertia:organization:install {--path= : Override migrations directory (default: database/migrations)}';
    protected $description = 'Generate the consolidated migration that introduces organization_id across declared tables and RBAC.';

    public function handle(): int
    {
        if (! OrganizationsFeature::isActive()) {
            if (config('innertia.mode') === 'api') {
                $this->error('Refusing to run: Organizations feature is inactive in api mode.');
            } else {
                $this->error('Refusing to run: config(innertia.organizations.enabled) is not true.');
            }
            return self::FAILURE;
        }

        $tables = config('innertia.organizations.tables', []);
        if (! is_array($tables)) {
            $this->error('innertia.organizations.tables must be an array.');
            return self::FAILURE;
        }

        // RBAC + identity always scoped — non-negotiable when feature is enabled.
        // Includes:
        //   - roles / model_roles    → roles per-org (existing)
        //   - model_permissions      → direct permission grants per-org
        //   - user_apps              → app access per-org (un user puede ser técnico en
        //                              org A pero backoffice en org B)
        $rbacTables = ['roles', 'model_roles', 'model_permissions', 'user_apps'];
        $allTables  = array_values(array_unique(array_merge($tables, $rbacTables)));

        $dir = $this->option('path') ?: database_path('migrations');
        File::ensureDirectoryExists($dir);

        $existing = glob($dir . '/*_add_organization_id_*.php') ?: [];
        if (count($existing) > 0) {
            $this->info('Migration already exists at ' . $existing[0] . ' — nothing to do.');
            return self::SUCCESS;
        }

        $timestamp = date('Y_m_d_His');
        $filename  = "{$timestamp}_add_organization_id_to_innertia_tables.php";
        $path      = $dir . DIRECTORY_SEPARATOR . $filename;

        $column    = config('innertia.organizations.column', 'organization_id');
        $withIndex = (bool) config('innertia.organizations.with_index', true);

        $body = $this->renderStub($allTables, $column, $withIndex);
        File::put($path, $body);

        $this->info('Created migration: ' . $path);
        $this->line('Run `php artisan migrate` to apply it.');

        return self::SUCCESS;
    }

    private function renderStub(array $tables, string $column, bool $withIndex): string
    {
        $upBlocks   = [];
        $downBlocks = [];

        foreach ($tables as $table) {
            $upBlocks[] = $this->renderUpBlock($table, $column, $withIndex);
            $downBlocks[] = $this->renderDownBlock($table, $column, $withIndex);
        }

        $up   = implode("\n\n", $upBlocks);
        $down = implode("\n\n", array_reverse($downBlocks));

        return <<<PHP
<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

/**
 * innertia-laravel — Organizations install migration.
 *
 * Adds `{$column}` (nullable bigint) to every declared table plus
 * `roles` and `model_roles`. NULL means "global to the tenant".
 *
 * Generated by `php artisan innertia:organization:install`.
 */
return new class extends Migration
{
    public function up(): void
    {
{$up}
    }

    public function down(): void
    {
{$down}
    }
};
PHP;
    }

    private function renderUpBlock(string $table, string $column, bool $withIndex): string
    {
        $indexLine = $withIndex
            ? "            \$table->index(['tenant_id', '{$column}'], '{$table}_tenant_org_idx');"
            : '';

        return <<<PHP
        Schema::table('{$table}', function (Blueprint \$table) {
            if (! Schema::hasColumn('{$table}', '{$column}')) {
                if (Schema::hasColumn('{$table}', 'tenant_id')) {
                    \$table->unsignedBigInteger('{$column}')->nullable()->after('tenant_id');
{$indexLine}
                } else {
                    \$table->unsignedBigInteger('{$column}')->nullable();
                    \$table->index('{$column}', '{$table}_org_idx');
                }
            }
        });
PHP;
    }

    private function renderDownBlock(string $table, string $column, bool $withIndex): string
    {
        return <<<PHP
        Schema::table('{$table}', function (Blueprint \$table) {
            if (Schema::hasColumn('{$table}', '{$column}')) {
                try { \$table->dropIndex('{$table}_tenant_org_idx'); } catch (\\Throwable \$e) {}
                try { \$table->dropIndex('{$table}_org_idx'); } catch (\\Throwable \$e) {}
                \$table->dropColumn('{$column}');
            }
        });
PHP;
    }
}
