<?php

namespace Innertia\Platform\Organizations\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Innertia\Platform\Organizations\OrganizationsFeature;

/**
 * Generates a single consolidated migration that:
 *   - Adds `organization_id` (nullable bigint) to every table declared in
 *     config('innertia.organizations.tables').
 *   - Adds `organization_id` to `roles` and `model_roles` (RBAC scope).
 *   - Adds a composite (tenant_id, organization_id) index when the table has tenant_id,
 *     otherwise a single-column index on organization_id.
 *
 * Guard: refuses to run unless the Organizations feature is active
 * (config('innertia.organizations.enabled')=true AND config('innertia.mode')!=='api').
 * Idempotent: re-running detects existing `*_add_organization_id_*.php` and skips.
 */
class OrganizationInstallCommand extends Command
{
    protected $signature = 'innertia:organization:install
        {--path= : Override migrations directory (default: database/migrations)}
        {--force : Generate a new migration even if a previous one exists. Útil cuando agregás tablas a config.tables después del install inicial. La migración usa Schema::hasColumn() para saltar columnas ya existentes — segura de aplicar.}';

    protected $description = 'Generate the consolidated migration that introduces organization_id across declared tables and RBAC.';

    public function handle(): int
    {
        if (! OrganizationsFeature::isActive()) {
            if (config('innertia.mode') === 'api') {
                $this->error('Refusing to run: Organizations feature is inactive in api mode.');
            } else {
                $this->error('Refusing to run: config(innertia.organizations.enabled) is not true.');
            }
            return self::FAILURE;
        }

        $tables = config('innertia.organizations.tables', []);
        if (! is_array($tables)) {
            $this->error('innertia.organizations.tables must be an array.');
            return self::FAILURE;
        }

        // RBAC + identity always scoped — non-negotiable when feature is enabled.
        $rbacTables = ['roles', 'model_roles', 'model_permissions', 'user_apps'];
        $allTables  = array_values(array_unique(array_merge($tables, $rbacTables)));

        $dir = $this->option('path') ?: database_path('migrations');
        File::ensureDirectoryExists($dir);

        $existing = glob($dir . '/*_add_organization_id_*.php') ?: [];
        if (count($existing) > 0 && ! $this->option('force')) {
            $this->info('Migration already exists at ' . $existing[0] . ' — nothing to do.');
            $this->line('Use --force to generate a new incremental migration (covers tables added to config since last install).');
            return self::SUCCESS;
        }

        $timestamp = date('Y_m_d_His');
        $filename  = "{$timestamp}_add_organization_id_to_innertia_tables.php";
        $path      = $dir . DIRECTORY_SEPARATOR . $filename;

        $column    = config('innertia.organizations.column', 'organization_id');
        $withIndex = (bool) config('innertia.organizations.with_index', true);

        $body = $this->renderStub($allTables, $column, $withIndex);
        File::put($path, $body);

        $this->info('Created migration: ' . $path);
        if (count($existing) > 0) {
            $this->line('Previous migration(s) detected:');
            foreach ($existing as $e) {
                $this->line('  • ' . basename($e));
            }
            $this->line('The new migration uses Schema::hasColumn() to skip tables that already have organization_id, so re-running migrate is safe.');
        }
        $this->line('Run `php artisan migrate` to apply it.');

        return self::SUCCESS;
    }

    private function renderStub(array $tables, string $column, bool $withIndex): string
    {
        $upBlocks   = [];
        $downBlocks = [];

        foreach ($tables as $table) {
            $upBlocks[] = $this->renderUpBlock($table, $column, $withIndex);
            $downBlocks[] = $this->renderDownBlock($table, $column, $withIndex);
        }

        $up   = implode("\n\n", $upBlocks);
        $down = implode("\n\n", array_reverse($downBlocks));

        return <<<PHP
<?php

use Illuminate\\Database\\Migrations\\Migration;
use Illuminate\\Database\\Schema\\Blueprint;
use Illuminate\\Support\\Facades\\Schema;

/**
 * innertia-laravel — Organizations install migration.
 *
 * Adds `{$column}` (nullable bigint) to every declared table plus
 * `roles` and `model_roles`. NULL means "global to the tenant".
 *
 * Generated by `php artisan innertia:organization:install`.
 */
return new class extends Migration
{
    public function up(): void
    {
{$up}
    }

    public function down(): void
    {
{$down}
    }
};
PHP;
    }

    private function renderUpBlock(string $table, string $column, bool $withIndex): string
    {
        $indexLine = $withIndex
            ? "            \$table->index(['tenant_id', '{$column}'], '{$table}_tenant_org_idx');"
            : '';

        return <<<PHP
        Schema::table('{$table}', function (Blueprint \$table) {
            if (! Schema::hasColumn('{$table}', '{$column}')) {
                if (Schema::hasColumn('{$table}', 'tenant_id')) {
                    \$table->unsignedBigInteger('{$column}')->nullable()->after('tenant_id');
{$indexLine}
                } else {
                    \$table->unsignedBigInteger('{$column}')->nullable();
                    \$table->index('{$column}', '{$table}_org_idx');
                }
            }
        });
PHP;
    }

    private function renderDownBlock(string $table, string $column, bool $withIndex): string
    {
        // No usamos try/catch para drop index: en Postgres una excepción dentro
        // del Schema::table() envenena la transacción y todo el rollback explota.
        // Detectamos índices existentes vía Schema::getIndexes() (Laravel 10.42+).
        return <<<PHP
        if (Schema::hasColumn('{$table}', '{$column}')) {
            \$existing = collect(Schema::getIndexes('{$table}'))->pluck('name')->all();
            Schema::table('{$table}', function (Blueprint \$table) use (\$existing) {
                if (in_array('{$table}_tenant_org_idx', \$existing, true)) {
                    \$table->dropIndex('{$table}_tenant_org_idx');
                }
                if (in_array('{$table}_org_idx', \$existing, true)) {
                    \$table->dropIndex('{$table}_org_idx');
                }
                \$table->dropColumn('{$column}');
            });
        }
PHP;
    }
}
